version: "3"
services:
  database:
    image: postgres:alpine
    container_name: lines-time-web-dev-database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lines_time